### ISSUE TITLE
Timestamp in CSV[BUG]

### ISSUE THREAD

**Issue by Kruzerson** [opensearch-project/reporting#1027] opened 2024-08-08 07:21 UTC
**Describe the bug**

Hello. When I try to create a report from a search, the "@timestamp" field is not displayed in the report. How can I add it there?

**To Reproduce**
1. Go to 'Discover'
2. Click on 'Reporting'
3. Create report
4. No Timestamp

**Expected behavior**
I want to see a timestamp in report

**OpenSearch Version**
v 2.15.0

**Dashboards Version**
v 2.15.0

**Screenshots**

![image (1)](https://github.com/user-attachments/assets/d6421c18-5cc1-4117-9649-cd5f11f1f85c)
![image](https://github.com/user-attachments/assets/18385cab-b411-4823-9010-9b1f0f48cc82)

**Comment by pawelw1** [comment] 2024-08-08 08:24
This issue is related to https://github.com/opensearch-project/reporting/issues/668 and https://github.com/opensearch-project/dashboards-reporting/issues/335 .

**Comment by dblock** [comment] 2024-08-26 16:23
[Catch All Triage - [1](https://github.com/andrross), [2](https://github.com/dblock), [3](https://github.com/AmiStrn), [4](https://github.com/reta), [5](https://github.com/finnegancarroll)]

**Comment by dblock** [comment] 2024-08-26 16:24
Someone from reporting should take a look, however maybe @frangabs you can help bisecting this regression to a commit?

**Comment by Kruzerson** [comment] 2024-09-23 12:11
@pawelw1 any changes?

**Comment by joshuali925** [comment] 2024-12-14 00:19
duplicate of https://github.com/opensearch-project/reporting/issues/668, see https://github.com/opensearch-project/reporting/issues/668#issuecomment-2542580759 for workaround. Fix will be tracked in https://github.com/opensearch-project/dashboards-reporting/issues/335

**Closed by joshuali925** 2024-12-14 00:19 UTC
Labels: bug
